### ISSUE TITLE
copying text doesn't work in Android

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#130]
![screenshot_2018-03-03-22-41-38](https://user-images.githubusercontent.com/5884000/36939692-812262ac-1f35-11e8-92a2-e05b7dda903c.png)

firefox nightly 60.0a1
nano adblocker 1.0.0.33

**Comment by jspenguin2017** [comment]
Honestly for Android you should try Brave browser. It's a problem in Ace, I'm not exactly sure how to fix this.

**Comment by hawkeye116477** [comment]
Brave Browser's Adblocker is so limited. It doesn't allow to add other filterlists than it's on Brave Adblocker and it doesn't support uBlock/Nano special rules of course and on Android it has practicaly no options.

**Comment by jspenguin2017** [comment]
OK, I'll add an option to let you choose which editor to use.

**Comment by jspenguin2017** [comment]
I've been testing on an emulator and CodeMirror doesn't work any better. Maybe it'll behave differently on a real device... 
I think browser extensions are pretty useless on Android though, as most of your ads are in apps.

**Comment by jspenguin2017** [comment]
There are many features in Ace that are deal breaker (advanced search, visual for line wrap, etc), so I'm not moving to CodeMirror. You can just use uBO on Android if you like CodeMirror better.

**Comment by krystian3w** [comment]
**Workaround:**

Buy Bluetooth / Micro USB Keyboard.

**Comment by hawkeye116477** [comment]
Maybe possible fix => https://github.com/ajaxorg/ace/issues/3675#issuecomment-394048821

**Comment by kgbm3** [comment]
Holy cow, someone had mentioned the Brave browser and I had to stop reading: "Brave is a free and open-source[4][5][6] pay-to-surf web browser based on the Chromium web browser [..]", because I threw up in my mouth a little. 

WTH does that mean, pay-to-anything and why - in the world - would anybody recommend such a thing, really - for whatever reason? o.0

**Comment by jspenguin2017** [comment]
Brave has its own cryptocurrency and let you support websites you use, but it is optional. I don't see anything wrong with it beside that I don't think it'll work out in the end. 

Brave doesn't let you subscribe to more filters but its adblocker is implemented in C++ which is way faster than any extension you can find. I don't use it on desktop because it is not customizable, but it is really good on Android.

**Comment by jspenguin2017** [comment]
Firefox build is no longer maintained by me, if this is still an issue, report to @LiCybora .

**Comment by krystian3w** [comment]
https://github.com/LiCybora/NanoCore2/commit/d4ead05480c4f69823df60e249259700a179d6dd

**Comment by jspenguin2017** [comment]
@krystian3w I don't understand what you wrote. For the commit you linked, I saw it yesterday, and I plan to look into updating Ace when I have time, maybe this weekend.

**Comment by krystian3w** [comment]
Maybe someone still use Nano in Firefox 68 ESR.

**Comment by jspenguin2017** [comment]
@krystian3w Okay...? Why are you telling me this? What are you expecting me to do with this information?

**Comment by krystian3w** [comment]
Don't be surprised how suddenly there are reports that you can't install an add-on in Firefox 77 / 78.

Additionally, ace has finally fixed the copy/cut to-touch option (mainly to the reporter and hawkeye).

**Comment by hawkeye116477** [comment]
@krystian3w It' should be rather information for @LiCybora, who maintain Firefox version.

**Comment by jspenguin2017** [comment]
@krystian3w 

I don't maintain the Firefox build, so you should contact `LiCybora` instead. 

I know Ace got an update, I will look into it.

**Comment by LiCybora** [comment]
There is nothing we can do because:
1. There is no way to install/debug addons on Fenix for now.
2. Even for the near release milestone they only plan to support Recommended Extension, while Nano is not.

Anyway, this is not a good place to discuss Firefox issue. If still have question, open new issue on my repo instead.
