### ISSUE TITLE
NanoAdblocker for Firefox

### ISSUE THREAD

**Issue by naters305** [NanoAdblocker/NanoCore#208]
This is more of a feature request than an issue with Nano. I have just recently switched to Firefox and would love to use Nano but it is not supported. If you are going to support Edge of all browsers I feel like you should support firefox as well.

**Comment by xlollomanx** [comment]
A few months ago nano adblocker was released on firefox store, but firefox removed it because have some "unsafe" code. For have it avaible again on official nano it needs to be completely rewrite and this it's a pain in a**. More info here: https://github.com/NanoAdblocker/NanoCore/issues/41#issuecomment-364144608
