### ISSUE TITLE
[Enhancement] Shortcut key for disabling selected filters in Filter Viewer

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#28]
many filter list block things you do not want

example. my anti donate filter list
`https://github.com/MajkiIT/polish-ads-filter/blob/master/anti-donate-filters/adblock_anty-dotacje.txt`

somebody don't want to block the bitcoin section in the filter list

what he can do
this someone must create own list or remove the filter list

this solution what i suggest would solve this problem

---

example. i click the green + button in bitcoin section, and filter has be disabled 

![2017-12-12 10_25_08-nano filter viewer](https://user-images.githubusercontent.com/5884000/33877137-c63e36b6-df27-11e7-8529-61e857b73342.png)

**Comment by mat41997** [comment]
and you can add a save button, to not to click by accident

**Comment by jspenguin2017** [comment]
I won't add save button to Filter Viewer, it doesn't make sense, it'll be overwritten when the filter update again. 
I don't see how to properly detect "section". I can have a special syntax for that, but I don't think many people will hop on my boat. I will add a "disable this filter" in Nano Logger though.

**Comment by mat41997** [comment]
special syntax, it seems to be okay

**Comment by jspenguin2017** [comment]
Yea but it won't fold your filters, only filters designed for Nano...

**Comment by mat41997** [comment]
yes
you must use a 
`!` before special syntex

example.
!$ site.com#img

**Comment by jspenguin2017** [comment]
I'm thinking 
```
!@nano-section [section name]
stuff
!@nano-endsection
```

**Comment by mat41997** [comment]
must be a react on click, to be easy

**Comment by jspenguin2017** [comment]
I can't easily make a toggle like that...

**Comment by jspenguin2017** [comment]
Although this is a reasonable functionality to add, the difficulty is way too high versus how useful it will be for the average person. It'll be on the bottom of to-do list at best.

**Comment by mat41997** [comment]
you can save in cache?

**Comment by jspenguin2017** [comment]
There isn't a reasonable way to detect "section", what I can do is add a shortcut key for disabling selected filters. 
Can be a bit difficult though.

**Comment by elypter** [comment]
cant this be done with whitelisting in the custom filters?

i think a more widely usable approach would be to make filterlists as a whole switchable. maybe as a checkbox combobox in the drop down panel. since the list can get quite long i would either add a checkbox after every filterlist that defines if it shows up in the combobox or allow to make custom groups.

this would allow users to for example whitelist ads but still block tracking, enable social share buttons just on one site or disable experimental filters on sites where they misbehave.

i dont know if this would be easy to implement because i assume that ublock interally merges all lists and gets rid of dublicates. it will be difficult to track which filters have to be enabled or disabled so the list has to be recompiled as soon as a list is being checked or unchecked. not too big of a deal but if you want to allow per site settings then you would have to keep multiple lists to avoid recompilation on every page load. or you have a global merged list and avoid merging on pages with custom settings.

**Comment by jspenguin2017** [comment]
To turn the entire filter list off you just do that in the dashboard. 

It's not always possible to neutralize a filter with custom filters. For example, `badfilter` and cosmetic filter exceptions cannot be reversed.

**Comment by elypter** [comment]
but its a hastle to click through the whole interface just to make a wesite work and then to switch it back on after you left and you can only do it globally and not on a per site basis

**Comment by jspenguin2017** [comment]
Like different filters for each domain? That makes no sense.

**Comment by jspenguin2017** [comment]
I think it's up to filter maintainers to separate filters that does different things into different files. There isn't a clean way to override the filters, and when it updates, the old overriding rules will no longer work properly.

**Comment by jspenguin2017** [comment]
I will, however, add a button to Logger that disable selected rule, and make 3rd party filters panel less painful to use.
