### ISSUE TITLE
[Suggestion] Reddit

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#31]
i think you can create a reddit
`https://www.reddit.com/`

to by build the community around the project NanoAdblocker

**Comment by jspenguin2017** [comment]
No, I'll keep it Nano so the name is different enough. I don't want people to think Nano is just another clone trying to scam users. 
I think Reddit is a better idea... But not sure, we are just starting, this is probably for later.

**Comment by lewisje** [comment]
I think that a publicly viewable service, like Reddit, where you can view other people's posts without an account, would be a better idea.

**Comment by mat41997** [comment]
ok, redit. let it be

**Comment by jspenguin2017** [comment]
I don't really want to run a subreddit, so if someone wants to run one for Nano, please let me know.

**Comment by lewisje** [comment]
Someone did make a subreddit and set it to private: https://www.reddit.com/r/NanoAdblocker

**Comment by jspenguin2017** [comment]
I just got a Reddit account: https://www.reddit.com/user/jspenguin2017/
Does anyone know who owns the name?

**Comment by reunicorn** [comment]
I don't know who the owner is, but I do know that you can [message them](https://www.reddit.com/message/compose/?to=/r/NanoAdblocker) to find out :)

**Comment by elypter** [comment]
there is a chance to claim the subreddit if it has been abandoned by the owner https://www.reddit.com/r/redditrequest/ but you have to have at least 500 karma and a 3 months old account

**Comment by jspenguin2017** [comment]
Well, that'll be a long time away.

**Comment by lewisje** [comment]
I'm not the creator of the sub, but I am the only mod, and the sub has no posts; I just invited you.

**Comment by jspenguin2017** [comment]
Cool. Thx. Anyone got a good stylesheet for the subreddit?

**Comment by Bisaloo** [comment]
> And is the subreddit still private?

Yes

> Anyone got a good stylesheet for the subreddit?

https://github.com/Axel--/Naut-for-reddit is pretty popular

**Comment by jspenguin2017** [comment]
@Bisaloo OK, I tested it out, although it looks good, the theme doesn't really fit, so we might need to fork it...

**Comment by jorgegonzalez** [comment]
Hello, just wanted to take credit for creating the subreddit for you guys!

**Comment by jspenguin2017** [comment]
I'll call this fixed for now, styling the subreddit will be for future expansion.

**Comment by xlollomanx** [comment]
Sorry for open this issue again but @jspenguin2017 have you ever think to start a thread on https://forum.xda-developers.com/ ? They are focused on smartphone world but they have section for others things too and they have nice mods. xda is a community made of developers and here you maybe found someone that can help you to mainting nano on a variety of browsers. Cheers.

**Comment by jspenguin2017** [comment]
@xlollomanx Do you want to start one? I don't have an account there.

**Comment by xlollomanx** [comment]
@jspenguin2017 yes I can. Tomorrow I think how introduce you and your work. I'll post a draft here.

**Comment by xlollomanx** [comment]
Sorry for the delay I forgot yesterday is saturday :). Ok this is what i think:  

Hello, I'm here to speak for a great developer named jspenguin. Since he doesn't own an xda account he asked me to open a thread here to ask help on his project. Let me introduce his work: he developed many open source addons for browsers (mainly chrome). Their main purpose is to block anti-adblock. Just to name a few of this: Adblock Protector and AAK-Cont (links of their repository: https://github.com/jspenguin2017/uBlockProtector & https://gitlab.com/xuhaiyang1234/AAK-Cont).
Recently he started to develop even an adblocker (based on ublock origin but with more in deepth settings) with his companion, they are called Nano Adblocker and Nano Defender (on chrome web store they can be found here: https://chrome.google.com/webstore/search/nano%20adblocker?utm_source=chrome-ntp-icon , the repos instead here: https://github.com/NanoAdblocker/NanoCore). They work together to block ads and anti-adblock and they are a war machine for what i can say a the moment.
This project become bigger and bigger and he started to support other browser like Firefox and Edge but this very impegnative, so he is looking for other devs that can help him to maintain this addons for Firefox and Edge. Feel free to contact him at this ?email? or his github repo.
I hope I choose the right section, thanks for your patience.

I'm thinking something like this @jspenguin2017 feel free to edit, change any things and let me know :)

**Comment by jspenguin2017** [comment]
I'll maintain Edge version, so I just need maintainers for Firefox version and maybe Safari if someone wants to try. Open a new issue to let me know.

**Comment by xlollomanx** [comment]
Ok I opened a forum, I hope someone will help you @jspenguin2017 . this is the link: https://forum.xda-developers.com/coding/web-apps/help-request-nano-adblocker-t3765483
