### ISSUE TITLE
No Search Option for My Filters

### ISSUE THREAD

**Issue by jputting** [NanoAdblocker/NanoCore#336]
Hi,

I have tried using Nano Adblocker 1.0.0.147 installed in Firefox 76.0.1(64Bit) on macOS  Catalina, Version 10.15.4

I am quite surprised to discover that the "My Filters" has NO search function.

I do hope this is corrected very quickly as I have a lot of custom filters and if one of them is interfering with a website I need to find it quickly and easily to modify or remove it.

This is a real deal breaker of an issue for myself as it is a  must have function I can't live without.

I can't understand why it is not there as the latest version of u Block Origin has retained it.

Please fix this as rapidly as possible.

**Comment by jspenguin2017** [comment]
`Ctrl+F` is the universal hotkey for search, this is the case for basically all applications. The hotkey is required to bring up Nano Editor's search box, it has been like this for a long time, even before uBlock Origin got its CodeMirror-powered filter editor. As a reminder, this is what uBlock Origin's filter editor used to look like: 
![image](https://user-images.githubusercontent.com/7283682/82766459-9700cf00-9ddc-11ea-92f3-6757fe95aefb.png)

Hotkeys are required to effectively use Nano Editor, this is by design. `Ctrl+S` to save, `Ctrl+/` to toggle comment, etc. Just like an IDE. 

If you like uBlock Origin's filter editor better, then uBlock Origin is better suited for your need.

**Comment by jputting** [comment]
Hi,

Yes I agree it's time to go back to u Block Origin.

It's so disappointing to see such inflexibility and poor design changes made without a very strong supporting rationale to validate a change.

Nobody here has yet put forward any good strong rational reasons as to why this decision was made to make Nano Adblocker slightly more difficult to use.

It's unfathomable to me why this change was made, when Gorhill has not seen the need to remove this "My Filters" search function. 

Unlike Nano adblocker Gorhill has not made his u Block Origin more difficult to use.

**Comment by llacb47** [comment]
Did you read?  

` The hotkey is required to bring up Nano Editor's search box, it has been like this for a long time, even before uBlock Origin got its CodeMirror-powered filter editor.`

Sorry to say but if you are incapable of using/do not want to use an _extremely_ common keyboard shortcut that's not Nano's fault.

**Comment by jputting** [comment]
Did you read?

I have memory issues and it is simply impossible to remember multiple keyboard commands and if I written notes they eventually get lost.

However it is Nano's fault when they for no valid reason remove a feature which makes using Nano easier.

**Comment by jspenguin2017** [comment]
This is not a design *change*, as Nano Editor was designed and created *before* uBlock Origin's new filter editor.

**Comment by jputting** [comment]
Thank you for clarifying that point for me, I was not aware that was the case.

Perhaps consideration could be given to implementing u Block Origin's filter editor, purely for making Nano Adblocker as easy to use as possible.

As previously stated with regret I have no other choice but to uninstall Nano Adblocker and return to u Block Orign

**Comment by jspenguin2017** [comment]
I have thought about switching to CodeMirror, but it behaves quite differently and I don't like that. 

Don't have regret for choosing the extension you like. Nano Adblocker was designed from the start for power users, it was never designed to fit every use case.

**Comment by LiCybora** [comment]
Since the OP claims using on Firefox and probably commented on store, I should make a reply here.

I somehow agree to put back the searchbox instead of hotkey. One of use case is using tablet or mobile device where `Ctrl+F` is not easily triggered, although mobile device is not yet officially supported. 

Maybe I should try to implement on downstream to take care those mobile users?

**Comment by jspenguin2017** [comment]
> @LiCybora 
> put back the searchbox

The search box was never "taken out", rather, Nano Editor and uBlock Origin's filter editor are completely different. So this might be more complicated than you expect. 

I think most tablets have `Ctrl` key on their touch keyboard, but there could certainly be an option to show the search box by default. I am thinking about a checkbox under `User interface`, along with the soft wrap settings. This should be the safest option and should not be too hard. Feel free to send a PR to implement this. 

If you wish to reimplement Nano Editor and Linter (syntax highlighting, annotations, etc.) on top of uBlock Origin's filter editor, that is fine too, and I will be more than happy to review your PR.
