### ISSUE TITLE
Make fixed headers static

### ISSUE THREAD

**Issue by hawkeye116477** [NanoAdblocker/NanoCore#83]
### Describe the issue (Required)
I write for request of @blocker999. Is it possible to make setting to transform fixed (movable) headers on all pages to static for Nano Adblocker?

### Screenshots (Required)
![header](https://user-images.githubusercontent.com/19818572/34630362-1051c7ca-f26c-11e7-98a7-57811982fd6d.png)

**Comment by jspenguin2017** [comment]
Unfortunately, it looks like you'll need a case-by-case rule. 
It's really hard to tell what is a "header" and what is other fixed element.

**Comment by elypter** [comment]
i am currently working on a userscript that does exactly that. it's not perfect but it works for most sites and doesnt have many false positives. i would prefer an implementation that uses parts of an adblocker because this script partially reimplements an adblocker and i dont know why some headers are not being detected and performance also isn't super efficient and can never be as good as an adblocker.

https://greasyfork.org/de/scripts/36901-blockhead
https://github.com/elypter/BlockHead

**Comment by jspenguin2017** [comment]
That's the problem, I can take a well-tested filter list that patches the headers of big websites, a generic solution is likely not to be possible.

**Comment by elypter** [comment]
the userscript that i made is pretty generic and works reasonably well. what it does is to look for elements with the getcomputedstyle containing position:fixed and then check the tagname, id and class names of that element whether it contains a keyword of a blacklist and a whitelist. if it matches a keyword in the blacklist and none in the whitelist then a "style='position:relative" gets added. with a good blacklist and a good whitelist this creates quite accurate results. there is nothing an adblocker could do as well. the question is just if this fits the addon or if it would be better to delegate some parts of that process to a script snippet or an external call of a userscript which is what the suggestion i made a while ago was about. i think that at least the part of looking up all the elements with position:fixed is something an adblocker is perfect for.

**Comment by jspenguin2017** [comment]
If you write a good tree walker then there is no reason for an Userscript to be slower.

**Comment by jspenguin2017** [comment]
Using the right tool for the job will yield better results, for this case, I think a style injection filter list or an Userscript (if you want to be generic) is probably the right tool.

**Comment by elypter** [comment]
you are kind of forced to go the user script route because gorhill hates generic cosmetic filters. before i wrote that userscript i made a generic filterlist. it is several MB in size because i have to repeat each of the rules 20 times for each of the most common top level domain because ublock origin ignores generic ones. thats the reason why i wrote this userscript in the first place. all just because he thinks that crippling he engine will increase performance. this is like burning your car to save the money on gasoline because you wont be able to drive anymore.

**Comment by jspenguin2017** [comment]
I can take a pull request for https://github.com/NanoAdblocker/NanoCore/issues/25

**Comment by elypter** [comment]
unfortunately i do not have any expierience in firefox or webextension addons and especially not this quite complex one. the userscript was by far the most code i ever wrote in javascript. i know it's annoying if people always ask for stuff and you feel like you are the only person responsible and people dump their software problems on you and expect solutions.
