### ISSUE TITLE
Why don't you merge Nano Adblocker to uBlock Origin?

### ISSUE THREAD

**Issue by davidhedlund** [NanoAdblocker/NanoCore#93]
uBlock Origin is the second most popular add-on om AMO.

Have you made any Pull request to uBlock Origin?

Don't you want your project to be part or uBO?

Or don't uBo want your code?

Please describe the philosophical differences between the projects and why this should be a separate project.

**Comment by davidhedlund** [comment]
https://github.com/NanoAdblocker/NanoDefender/issues/11

**Comment by jspenguin2017** [comment]
I have a different vision than gorhill and we disagree on some things.

**Comment by davidhedlund** [comment]
Can you please explain this on https://addons.mozilla.org/en-US/firefox/addon/real-nano-adblocker/ ?

**Comment by jspenguin2017** [comment]
The textbox is too small, it doesn't fit.

**Comment by davidhedlund** [comment]
Can you explain it at https://github.com/NanoAdblocker/NanoCore or somewhere else then?

**Comment by jspenguin2017** [comment]
Gorhill disagree with pretty much every change I made, I don't see a value in telling everyone how I disagree with gorhill.

**Comment by davidhedlund** [comment]
I'm sure people want to know **why** you started the project.

**Comment by jspenguin2017** [comment]
I just want to tweak uBO to my liking. Many changes will be subjective. 
I don't think this adds any value to the README.

**Comment by davidhedlund** [comment]
Do as you want but some people will remain confused.

**Comment by jspenguin2017** [comment]
If someone really wants to know, he would have asked (like what you did), or search for related issues if there are any (there is one now). 
I don't think highlighting my disagreement with gorhill add any value to the description.

**Comment by cucumbur** [comment]
It made me stick to using ublock origin because all I saw was gorhills dickishness being returned in kind, even if it wasn't explicit. if it was explicit you could at least explain it in a narrative that doesn't point to either dev / project as an asshole, just different goals. I would switch to Ad Nauseam but I have a feeling the maintainers and contributors are equally as caustic

**Comment by DFNCTSC** [comment]
@jspenguin2017 If you simply addressed the issue, answered it publicly and stated the endgame, it would be nice. Simply because, if you are as dedicated as gorhill, you need more exposure and I think since gorhill is so stubborn you could [have] be[en] the king of adblockers.

**Comment by jspenguin2017** [comment]
Although I did implement a few useful features when this project started, I haven't been working on it a lot lately. Gorhill is clearly way more dedicated to his projects and he has significantly more time to work on them. I don't want to commit to a specific roadmap, I'll simply add or change features as I see fit when I have time.

**Comment by DFNCTSC** [comment]
@jspenguin2017 Ahh. Thank you very much for a candid response. Feels a lot better knowing you're a human too. :P 

I really very much value and appreciate your work. Hope you have a great holidays.

**Comment by filips123** [comment]
@spenguin2017 Has now anything changed?

I still think it would be useful to marge Nano Adblocker into uBlock Origin and support at least optional, but supported, Nano Adblocker's lists and other features. It may be better both for you and uBlock Origin?

Which specific things were that you disagreed with gorhill? Would be possible to adress them?

**Comment by jspenguin2017** [comment]
@filips123 The changes I made are mostly subjective, so I believe it is not worth to spend the time to reach an agreement with upstream. If there are any features that you really like, you are more than welcomed to suggest them in the upstream issues tracker.

**Comment by gethubb** [comment]
> @filips123 The changes I made are mostly subjective, so I believe it is not worth to spend the time to reach an agreement with upstream. If there are any features that you really like, you are more than welcomed to suggest them to the upstream issues tracker.

Hello there,

I've been using uBlock Origin ever since I learned years ago that it had advantages over Adblock Plus. Today, reading into filter lists, I saw mention of Nano Adblocker.

I found this thread by Googling "ublock vs nano". I would invite you to consider that a number of the folks who make that search are not familiar with the developers of the software they're researching and wouldn't want to cause any drama, but just want a simple answer... what's up with these two visually similar, functionally similar tools?

Funnily enough, I took a pause and did a bit more searching--do you mind if I quote your (ostensibly) post from a year back on a social news site?

>It's mainly because I disagree with gorhill on a few features:

>- Syntax highlighter and linter -- gorhill doesn't want the performance hit (but I think it's worth it)

>- Issues reporting server -- gorhill doesn't want a "home server" (but I think having a central reports processing server increases privacy as all reports will be posted by NanoMeow which makes the reports more anonymous)

>- Privileged script snippets -- gorhill doesn't like the idea

>Note that the extra filter lists is more for my own convenience, it's not a meaningful difference as you can subscribe to any filters you like.

That is a very reasonable comparison you made. I don't understand each issue, but others will. They'll decide which philosophy they prefer, install an extension accordingly, and forget about it until the next shiny new adblocker comes along.

I respect that you didn't want to mudsling, though, I will say. But it's no problem. Different people, different opinions, mutual respect.

I'm sticking with uBlock Origin until I see it's ineffective, slow, or sells out... or that shiny new one comes along. Meanwhile, I hope somebody finds the above copy/paste useful.

Cheers friend, thank you for the volunteer effort to improve our security and collective web experience!

**Comment by jspenguin2017** [comment]
> but just want a simple answer...

For people who just want to know the notable differences, it's in the README: https://github.com/NanoAdblocker/NanoCore#notable-changes
